### ISSUE TITLE
"can't read user database" when mountOptions sets uid

### ISSUE THREAD

**Issue by stv0g** [calponia/csi-driver-davfs#1]
First of all: thanks a lot for this CSI driver 👍 

I encountered a small issue when I try to mount WebDav shares for non-root users.

##### Resources
```
---
apiVersion: v1
kind: Secret
metadata:
  name: sciebo-3dpt00-rwth-aachen-de
  namespace: jhub-users
data:
  username: 3DPT00@rwth-aachen.de
  password: xxxx
type: Opaque
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sciebo-3dpt00-rwth-aachen-de
  namespace: jhub-users
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      username: 3dpt00-rwth-aachen.de
      server: rwth-aachen.sciebo.de
      share: csi-driver-davfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sciebo-3dpt00-rwth-aachen-de
  namespace: jhub-users
  labels:
    username: 3dpt00-rwth-aachen.de
    server: rwth-aachen.sciebo.de
    share: csi-driver-davfs
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
  - uid=1000
  - gid=100
  csi:
    driver: csi-davfsplugin
    volumeHandle: data-id
    volumeAttributes:
      server: https://rwth-aachen.sciebo.de
      share: /remote.php/webdav/
    nodePublishSecretRef:
      name: sciebo-3dpt00-rwth-aachen-de
      namespace: jhub-users
```

Please note the following `mountOptions` in the PV which are required for making the mountpoint accessible by non-root users:

```
  mountOptions:
  - uid=1000
  - gid=100
```

Unfortunately, this gives me the following error during the attachment:

> can't read user database

which is raised here: https://github.com/volga629/davfs2/blob/8bad5be1e370d527f89144cfbfe64f6a0a014390/src/mount_davfs.c#L1751

The error is caused by davfs2 trying to create a cache directory for the user (or read `~/.davfs.conf`) within its home directory. This obviously fails as the the user of my container is not available within the `csi-nodeplugin-davfsplugin` DS (container `davfs`).

##### Workaround

I was able to work around the issue by adding my user within the DS by using a container lifecycle hook to `davfs`.

```
apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: csi-nodeplugin-davfsplugin
        namespace: csi-davfs-system
      spec:
        template:
          spec:
            containers:
            - name: davfs
              lifecycle:
                postStart:
                  exec:
                    command:
                    - sh
                    - -c
                    - |
                      adduser -u 1000 -D jovyan
                      adduser jovyan users
```

Unfortunately, there seems to be no other possibility to fix this issue as davfs2 strictly requires that the user exists locally. I dont see a technical reason for it. So we may be able to work around it by patching davfs2.

A more elegant solution might be the dynamic addition of users from [NodePublishVolume](https://github.com/stv0g/csi-driver-davfs/blob/0c8edb4977c763b01c535d8f6de8e01018fff6d1/pkg/davfs/nodeserver.go#L39)?
